name: SQL Assignment Autograding

on:
  push:
    branches:
      - main

jobs:

  mysql-test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: CollegeDB
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10


    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install mysql-client -y


    - name: Wait for MySQL
      run: |
        sleep 20


    - name: Execute Student SQL
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -proot < starter.sql


    - name: Run Test Cases
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -proot < testcase.sql


    - name: Assignment Completed
      run: |
        echo "SQL Assignment Passed Successfully"
